services:
  desktop-x11:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6080:6080"
    environment:
      VNC_RESOLUTION: "1280x800"
      VNC_DEPTH: "24"
    shm_size: 256m
